### ISSUE TITLE
use fork or upstream?

### ISSUE THREAD

**Issue by juju4** [CIRCL/pystemon#6]
is the recommendation to use this fork with CIRCL projects/in general or upstream?

Note: with pyaml 5.1+, yaml.load() error per  https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
https://github.com/CIRCL/pystemon/blob/master/pystemon.py#L871
https://github.com/CIRCL/pystemon/blob/master/pystemon.py#L880
fixed in upstream https://github.com/cvandeplas/pystemon/blob/2743b7a22120319be0e9b222813e3bc2c5024802/pystemon/config.py#L304

**Comment by Terrtia** [comment]
Hi @juju4 !
Thanks for the report !
It's best if you use cvandesplas repository. This repository is outdated

**Comment by juju4** [comment]
Thanks for confirmation.
